test_that("user registration is explicit, normalized, lossless and removable", {
  data <- withr::local_tempdir()
  withr::local_envvar(R_USER_DATA_DIR = data)
  root <- .warm_start_registry_root("user")
  expect_true(startsWith(root, data))
  expect_false(dir.exists(root))
  empty <- list_warm_start_models("user")
  expect_equal(nrow(empty), 0)
  expect_false(dir.exists(root))
  expect_error(load_warm_start_model(name = "missing", source = "user"), "No registered")
  expect_false(dir.exists(root))
  model <- warm_core_model()
  path <- register_warm_start_model(model, "  My_Model  ")
  expect_identical(basename(path), "my-model.rds")
  expect_identical(load_warm_start_model(name = "MY MODEL", source = "user"), model)
  expect_error(register_warm_start_model(model, "my model"), "already exists")
  model <- prepare_warm_start_model(model, list(version = "2026.1", domain = "synthetic"))
  expect_identical(register_warm_start_model(model, "my-model", TRUE), path)
  register_warm_start_model(warm_core_model(), "another")
  rows <- list_warm_start_models("user")
  expect_identical(rows$name, c("another", "my-model"))
  expect_identical(rows$source, rep("user", 2))
  expect_true(is.na(rows$version[1]))
  expect_identical(rows$version[2], "2026.1")
  expect_identical(rows$metadata[[2]], model$metadata)
  expect_true(all(rows$size_bytes > 0))
  expect_null(rows$validation[[1]])
  removed <- remove_warm_start_model("MY_MODEL")
  # Resolve the surviving parent: the artifact itself has already been removed.
  expect_identical(
    file.path(normalizePath(dirname(removed), winslash = "/", mustWork = TRUE), basename(removed)),
    path
  )
  expect_false(file.exists(path))
  expect_error(remove_warm_start_model("my-model"), "does not exist")
  expect_identical(nrow(list_warm_start_models("user")), 1L)
})

test_that("names, corrupt entries and redirected package roots fail clearly", {
  data <- withr::local_tempdir()
  withr::local_envvar(R_USER_DATA_DIR = data)
  model <- warm_core_model()
  for (name in list(NULL, NA_character_, "", "../escape", "a/b", "a\\b", ".", "a.rds", "-a", "a--b",
                    "a-", "é", c("a", "b"), 1)) {
    expect_error(register_warm_start_model(model, name), "name")
  }
  expect_error(register_warm_start_model(model, "valid", overwrite = NA), "TRUE or FALSE")
  root <- .warm_start_registry_root("user")
  expect_false(dir.exists(root))
  path <- register_warm_start_model(model, "valid")
  writeLines("corrupt", path)
  expect_error(list_warm_start_models("user"), "valid.rds")
  expect_error(load_warm_start_model(name = "valid", source = "user"), "valid.rds")
  remove_warm_start_model("valid")
  saveRDS(model, file.path(root, "UPPER.rds"))
  expect_error(list_warm_start_models("user"), "Noncanonical")
  unlink(file.path(root, "UPPER.rds"))
  dir.create(file.path(root, "directory.rds"))
  expect_error(load_warm_start_model(name = "directory", source = "user"), "Invalid")
  package <- system.file(package = "pairwiseLLM")
  expect_error(.warm_start_user_root_safe(file.path(package, "models")), "installed package")
  expect_error(.warm_start_user_root_safe(file.path(package, "new", "nested")), "installed package")
  expect_true(.warm_start_within("/root/models/a.rds", "/root/models"))
  expect_false(.warm_start_within("/root/models-other/a.rds", "/root/models"))
  expect_identical(.warm_start_registry_entry("", "valid"), "")
  # A file in place of the registry parent must cause a clean creation failure.
  blocked <- file.path(data, "blocked")
  writeLines("file", blocked)
  local_mocked_bindings(.warm_start_registry_root = function(...) file.path(blocked, "models"))
  expect_error(register_warm_start_model(model, "valid"), "Cannot create")
})

test_that("bundled lookup shares the public load path and ambiguity requires source", {
  data <- withr::local_tempdir()
  bundle <- withr::local_tempdir()
  withr::local_envvar(R_USER_DATA_DIR = data)
  root <- .warm_start_registry_root("user")
  local_mocked_bindings(.warm_start_registry_root = function(source) {
    if (source == "user") root else bundle
  })
  user <- warm_core_model()
  bundled <- warm_bundle_model("same")
  warm_bundle_write(bundle, bundled)
  expect_identical(load_warm_start_model(name = "same"), bundled)
  register_warm_start_model(user, "same")
  expect_error(load_warm_start_model(name = "same"), "Ambiguous")
  expect_identical(load_warm_start_model(name = "same", source = "user"), user)
  expect_identical(load_warm_start_model(name = "same", source = "bundled"), bundled)
  expect_identical(load_warm_start_model(file.path(bundle, "same.rds")), bundled)
  expect_error(load_warm_start_model("same"), "does not exist")
  rows <- list_warm_start_models()
  expect_identical(rows$name, c("same", "same"))
  expect_identical(rows$source, c("bundled", "user"))
  expect_identical(rows$audit_status, c("summary_only", "full"))
  expect_identical(nrow(list_warm_start_models("bundled")), 1L)
  expect_identical(predict(load_warm_start_model(name = "same", source = "bundled"), warm_core_features()),
    predict(bundled, warm_core_features()))
  remove_warm_start_model("same")
  expect_true(file.exists(file.path(bundle, "same.rds")))
  expect_identical(load_warm_start_model(name = "same"), bundled)
  expect_error(remove_warm_start_model("same"), "does not exist")
})

test_that("registry operations reject escaping and dangling symlinks", {
  skip_on_os("windows")
  data <- withr::local_tempdir()
  external <- withr::local_tempdir()
  withr::local_envvar(R_USER_DATA_DIR = data)
  model <- warm_core_model()
  root <- .warm_start_registry_root("user")
  dir.create(root, recursive = TRUE)
  path <- file.path(external, "outside.rds")
  save_warm_start_model(model, path)
  link <- file.path(root, "escape.rds")
  expect_true(file.symlink(path, link))
  expect_error(load_warm_start_model(name = "escape", source = "user"), "escaping")
  expect_error(register_warm_start_model(model, "escape", TRUE), "escaping")
  expect_error(remove_warm_start_model("escape"), "escaping")
  expect_error(list_warm_start_models("user"), "escaping")
  expect_identical(readRDS(path), model)
  unlink(link)
  expect_true(file.symlink(file.path(external, "missing"), link))
  expect_error(register_warm_start_model(model, "escape", TRUE), "escaping")
  unlink(link)
  inside <- register_warm_start_model(model, "inside")
  expect_true(file.symlink(inside, link))
  expect_identical(load_warm_start_model(name = "escape", source = "user"), model)
  remove_warm_start_model("escape")
  expect_true(file.exists(inside))
})

test_that("failed removal leaves the user model available", {
  withr::local_envvar(R_USER_DATA_DIR = withr::local_tempdir())
  model <- warm_core_model()
  path <- register_warm_start_model(model, "retained")
  local_mocked_bindings(.warm_start_remove_file = function(path) 1L)
  expect_error(remove_warm_start_model("retained"), "Cannot remove")
  expect_identical(load_warm_start_model(path), model)
})
